# Generated by Django 3.0.8 on 2020-12-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MunicipioZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.IntegerField()),
                ('secao', models.IntegerField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('turno', models.IntegerField()),
                ('candidato_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.CandidatoPartido')),
                ('municipio_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.MunicipioZona')),
            ],
        ),
        migrations.AddField(
            model_name='candidatopartido',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Municipio'),
        ),
        migrations.AddField(
            model_name='candidatopartido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Partido'),
        ),
        migrations.AddField(
            model_name='candidatopartido',
            name='tipo_candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.TipoCandidato'),
        ),
    ]
